// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5fnRgVaT1HZPr8YN8K7quo4d99dJvANg',
    appId: '1:694446942730:web:f1ef4b6b929a7e44840df3',
    messagingSenderId: '694446942730',
    projectId: 'challenge-direct-solution',
    authDomain: 'challenge-direct-solution.firebaseapp.com',
    storageBucket: 'challenge-direct-solution.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfOV-r_6hnZZLYER9oYmHjGLc3CSmT7Lc',
    appId: '1:694446942730:android:cd9930accbdb3dec840df3',
    messagingSenderId: '694446942730',
    projectId: 'challenge-direct-solution',
    storageBucket: 'challenge-direct-solution.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-W9Ns1QJW2jj8Vcn-f0R8J3NY5TvqWbI',
    appId: '1:694446942730:ios:86cf016db569a5ce840df3',
    messagingSenderId: '694446942730',
    projectId: 'challenge-direct-solution',
    storageBucket: 'challenge-direct-solution.firebasestorage.app',
    iosBundleId: 'br.com.devamancio.challengeDirectSolution',
  );
}
